# stage 1
FROM node:14-alpine AS builder
WORKDIR /usr/src/app
COPY package.json ./
COPY yarn.lock ./
RUN yarn
COPY . .
RUN yarn build

# stage 2
FROM node:14-alpine
WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn --prod
COPY --from=builder /usr/src/app/dist .
EXPOSE 3000
CMD ["npm", "start"]